"""
Comparison Engine
Compares two analyzed user profiles (CSV vs Scraped or Username vs Username).
Calculates shared actors/directors, comparative statistics, side-by-side chart data,
and a cinema compatibility index.
"""
import math
from typing import Dict, Any, List


def calculate_cosine_similarity(vec1: Dict[str, int], vec2: Dict[str, int]) -> float:
    """Calculates cosine similarity between two frequency dictionaries."""
    keys = set(vec1.keys()).union(set(vec2.keys()))
    if not keys:
        return 0.0

    dot_product = sum(vec1.get(k, 0) * vec2.get(k, 0) for k in keys)
    norm1 = math.sqrt(sum(v ** 2 for v in vec1.values()))
    norm2 = math.sqrt(sum(v ** 2 for v in vec2.values()))

    if norm1 == 0 or norm2 == 0:
        return 0.0

    return min(1.0, max(0.0, dot_product / (norm1 * norm2)))


def compare_user_profiles(user1_data: Dict[str, Any], user2_data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Compares two user stat structures generated by aggregate_user_stats.
    Returns:
    - Compatibility score (0-100%)
    - Shared top directors & side-by-side chart data
    - Shared top actors & side-by-side chart data
    - Exclusive favorites for each user
    """
    user1_name = user1_data.get("label", "Primary User")
    user2_name = user2_data.get("label", "Comparison User")

    # Build maps for User 1
    u1_directors = {d["name"]: d for d in user1_data.get("directors", [])}
    u1_actors = {a["name"]: a for a in user1_data.get("actors", [])}

    # Build maps for User 2
    u2_directors = {d["name"]: d for d in user2_data.get("directors", [])}
    u2_actors = {a["name"]: a for a in user2_data.get("actors", [])}

    # 1. Shared Directors
    shared_directors = []
    for name, d1 in u1_directors.items():
        if name in u2_directors:
            d2 = u2_directors[name]
            career_total = max(d1.get("career_total", 0), d2.get("career_total", 0))
            shared_directors.append({
                "name": name,
                "profile_path": d1.get("profile_path") or d2.get("profile_path"),
                "user1_count": d1["count"],
                "user2_count": d2["count"],
                "combined_count": d1["count"] + d2["count"],
                "difference": abs(d1["count"] - d2["count"]),
                "career_total": career_total,
                "user1_completion_pct": d1.get("completion_pct", 0),
                "user2_completion_pct": d2.get("completion_pct", 0),
                "user1_profile_pct": d1.get("profile_pct", 0),
                "user2_profile_pct": d2.get("profile_pct", 0),
            })

    # Sort shared directors by combined count descending
    shared_directors.sort(key=lambda x: x["combined_count"], reverse=True)

    # 2. Shared Actors
    shared_actors = []
    for name, a1 in u1_actors.items():
        if name in u2_actors:
            a2 = u2_actors[name]
            career_total = max(a1.get("career_total", 0), a2.get("career_total", 0))
            shared_actors.append({
                "name": name,
                "profile_path": a1.get("profile_path") or a2.get("profile_path"),
                "user1_count": a1["count"],
                "user2_count": a2["count"],
                "combined_count": a1["count"] + a2["count"],
                "difference": abs(a1["count"] - a2["count"]),
                "career_total": career_total,
                "user1_completion_pct": a1.get("completion_pct", 0),
                "user2_completion_pct": a2.get("completion_pct", 0),
                "user1_profile_pct": a1.get("profile_pct", 0),
                "user2_profile_pct": a2.get("profile_pct", 0),
            })

    # Sort shared actors by combined count descending
    shared_actors.sort(key=lambda x: x["combined_count"], reverse=True)

    # 3. Chart Data: Top 10 side-by-side directors and actors
    chart_directors = [
        {
            "name": d["name"],
            "User1": d["user1_count"],
            "User2": d["user2_count"],
            "user1_label": user1_name,
            "user2_label": user2_name,
        }
        for d in shared_directors[:10]
    ]

    chart_actors = [
        {
            "name": a["name"],
            "User1": a["user1_count"],
            "User2": a["user2_count"],
            "user1_label": user1_name,
            "user2_label": user2_name,
        }
        for a in shared_actors[:10]
    ]

    # 4. Exclusive Favorites (User 1 has watched 2+, User 2 has watched 0 or 1)
    u1_exclusive_directors = [
        d for d in user1_data.get("directors", [])
        if d["name"] not in u2_directors or u2_directors[d["name"]]["count"] <= 1
    ][:5]

    u2_exclusive_directors = [
        d for d in user2_data.get("directors", [])
        if d["name"] not in u1_directors or u1_directors[d["name"]]["count"] <= 1
    ][:5]

    u1_exclusive_actors = [
        a for a in user1_data.get("actors", [])
        if a["name"] not in u2_actors or u2_actors[a["name"]]["count"] <= 1
    ][:5]

    u2_exclusive_actors = [
        a for a in user2_data.get("actors", [])
        if a["name"] not in u1_actors or u1_actors[a["name"]]["count"] <= 1
    ][:5]

    # 5. Compatibility Score
    # Jaccard overlap on movie titles
    u1_titles = {f.get("title", "").lower() for f in user1_data.get("films", []) if f.get("title")}
    u2_titles = {f.get("title", "").lower() for f in user2_data.get("films", []) if f.get("title")}
    shared_movies = u1_titles.intersection(u2_titles)
    
    movie_overlap_pct = (len(shared_movies) / max(len(u1_titles.union(u2_titles)), 1)) if (u1_titles or u2_titles) else 0

    # Vector similarity on director and actor frequencies
    u1_dir_vec = {d["name"]: d["count"] for d in user1_data.get("directors", [])}
    u2_dir_vec = {d["name"]: d["count"] for d in user2_data.get("directors", [])}
    dir_sim = calculate_cosine_similarity(u1_dir_vec, u2_dir_vec)

    u1_act_vec = {a["name"]: a["count"] for a in user1_data.get("actors", [])}
    u2_act_vec = {a["name"]: a["count"] for a in user2_data.get("actors", [])}
    act_sim = calculate_cosine_similarity(u1_act_vec, u2_act_vec)

    # Weighted Compatibility Index
    raw_score = (0.4 * dir_sim) + (0.4 * act_sim) + (0.2 * movie_overlap_pct)
    compatibility_score = round(min(100.0, max(5.0, raw_score * 100)), 1)

    return {
        "user1_name": user1_name,
        "user2_name": user2_name,
        "compatibility_score": compatibility_score,
        "shared_movies_count": len(shared_movies),
        "shared_movies_sample": list(shared_movies)[:10],
        "shared_directors_count": len(shared_directors),
        "shared_actors_count": len(shared_actors),
        "shared_directors": shared_directors,
        "shared_actors": shared_actors,
        "chart_directors": chart_directors,
        "chart_actors": chart_actors,
        "exclusives": {
            "user1_directors": u1_exclusive_directors,
            "user2_directors": u2_exclusive_directors,
            "user1_actors": u1_exclusive_actors,
            "user2_actors": u2_exclusive_actors,
        }
    }
