"""
Curated Cinema Dataset & Demo Profiles
Provides rich metadata for popular films, actors, and directors,
guaranteeing instant out-of-the-box demo functionality even without a live TMDB key.
"""

FAMOUS_DIRECTORS_CAREER = {
    "Christopher Nolan": 12,
    "Quentin Tarantino": 10,
    "Martin Scorsese": 26,
    "Steven Spielberg": 34,
    "Denis Villeneuve": 11,
    "David Fincher": 12,
    "Greta Gerwig": 4,
    "Wes Anderson": 11,
    "Bong Joon-ho": 8,
    "Hayao Miyazaki": 12,
    "Stanley Kubrick": 13,
    "Paul Thomas Anderson": 9,
    "Guillermo del Toro": 12,
    "Ridley Scott": 28,
    "Alfred Hitchcock": 53,
    "Jordan Peele": 3,
    "Damien Chazelle": 5,
    "Coen Brothers": 18,
    "Joel Coen": 19,
    "Ethan Coen": 18,
    "Yorgos Lanthimos": 8,
    "Park Chan-wook": 11,
    "Spike Lee": 24,
    "Alfonso Cuarón": 8,
    "James Cameron": 9,
}

FAMOUS_ACTORS_CAREER = {
    "Leonardo DiCaprio": 32,
    "Brad Pitt": 60,
    "Christian Bale": 45,
    "Robert De Niro": 110,
    "Al Pacino": 55,
    "Tom Hanks": 65,
    "Matt Damon": 70,
    "Cillian Murphy": 42,
    "Margot Robbie": 28,
    "Emma Stone": 30,
    "Florence Pugh": 22,
    "Timothée Chalamet": 24,
    "Ryan Gosling": 34,
    "Willem Dafoe": 105,
    "Samuel L. Jackson": 150,
    "Scarlett Johansson": 52,
    "Morgan Freeman": 88,
    "Gary Oldman": 68,
    "Joaquin Phoenix": 40,
    "Zendaya": 16,
    "Michael Caine": 130,
    "Tilda Swinton": 75,
    "Song Kang-ho": 40,
    "Daniel Kaluuya": 18,
    "Cate Blanchett": 62,
}

SAMPLE_MOVIES_METADATA = {
    "oppenheimer": {
        "title": "Oppenheimer",
        "year": 2023,
        "directors": [{"id": 525, "name": "Christopher Nolan"}],
        "cast": [
            {"id": 2037, "name": "Cillian Murphy", "character": "J. Robert Oppenheimer"},
            {"id": 1373737, "name": "Florence Pugh", "character": "Jean Tatlock"},
            {"id": 3223, "name": "Robert Downey Jr.", "character": "Lewis Strauss"},
            {"id": 1892, "name": "Matt Damon", "character": "Leslie Groves"},
            {"id": 5081, "name": "Emily Blunt", "character": "Kitty Oppenheimer"},
            {"id": 64, "name": "Gary Oldman", "character": "Harry S. Truman"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    },
    "interstellar": {
        "title": "Interstellar",
        "year": 2014,
        "directors": [{"id": 525, "name": "Christopher Nolan"}],
        "cast": [
            {"id": 10297, "name": "Matthew McConaughey", "character": "Cooper"},
            {"id": 1813, "name": "Anne Hathaway", "character": "Brand"},
            {"id": 83002, "name": "Jessica Chastain", "character": "Murph"},
            {"id": 1892, "name": "Matt Damon", "character": "Dr. Mann"},
            {"id": 3895, "name": "Michael Caine", "character": "Professor Brand"},
            {"id": 1190668, "name": "Timothée Chalamet", "character": "Young Tom"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    },
    "inception": {
        "title": "Inception",
        "year": 2010,
        "directors": [{"id": 525, "name": "Christopher Nolan"}],
        "cast": [
            {"id": 6193, "name": "Leonardo DiCaprio", "character": "Dom Cobb"},
            {"id": 24045, "name": "Joseph Gordon-Levitt", "character": "Arthur"},
            {"id": 27578, "name": "Elliot Page", "character": "Ariadne"},
            {"id": 2524, "name": "Tom Hardy", "character": "Eames"},
            {"id": 2037, "name": "Cillian Murphy", "character": "Robert Fischer"},
            {"id": 3895, "name": "Michael Caine", "character": "Miles"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    },
    "the dark knight": {
        "title": "The Dark Knight",
        "year": 2008,
        "directors": [{"id": 525, "name": "Christopher Nolan"}],
        "cast": [
            {"id": 3894, "name": "Christian Bale", "character": "Bruce Wayne / Batman"},
            {"id": 1810, "name": "Heath Ledger", "character": "Joker"},
            {"id": 3895, "name": "Michael Caine", "character": "Alfred Pennyworth"},
            {"id": 64, "name": "Gary Oldman", "character": "Jim Gordon"},
            {"id": 2037, "name": "Cillian Murphy", "character": "Jonathan Crane / Scarecrow"},
            {"id": 192, "name": "Morgan Freeman", "character": "Lucius Fox"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    },
    "dune: part two": {
        "title": "Dune: Part Two",
        "year": 2024,
        "directors": [{"id": 137427, "name": "Denis Villeneuve"}],
        "cast": [
            {"id": 1190668, "name": "Timothée Chalamet", "character": "Paul Atreides"},
            {"id": 505710, "name": "Zendaya", "character": "Chani"},
            {"id": 930850, "name": "Rebecca Ferguson", "character": "Lady Jessica"},
            {"id": 1373737, "name": "Florence Pugh", "character": "Princess Irulan"},
            {"id": 86654, "name": "Austin Butler", "character": "Feyd-Rautha"},
            {"id": 16851, "name": "Javier Bardem", "character": "Stilgar"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    },
    "dune": {
        "title": "Dune",
        "year": 2021,
        "directors": [{"id": 137427, "name": "Denis Villeneuve"}],
        "cast": [
            {"id": 1190668, "name": "Timothée Chalamet", "character": "Paul Atreides"},
            {"id": 930850, "name": "Rebecca Ferguson", "character": "Lady Jessica"},
            {"id": 74568, "name": "Oscar Isaac", "character": "Duke Leto Atreides"},
            {"id": 505710, "name": "Zendaya", "character": "Chani"},
            {"id": 16851, "name": "Javier Bardem", "character": "Stilgar"},
            {"id": 58369, "name": "Stellan Skarsgård", "character": "Baron Harkonnen"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    },
    "blade runner 2049": {
        "title": "Blade Runner 2049",
        "year": 2017,
        "directors": [{"id": 137427, "name": "Denis Villeneuve"}],
        "cast": [
            {"id": 30614, "name": "Ryan Gosling", "character": "K"},
            {"id": 3, "name": "Harrison Ford", "character": "Rick Deckard"},
            {"id": 224513, "name": "Ana de Armas", "character": "Joi"},
            {"id": 11090, "name": "Robin Wright", "character": "Lt. Joshi"},
            {"id": 7499, "name": "Jared Leto", "character": "Niander Wallace"},
            {"id": 564, "name": "Dave Bautista", "character": "Sapper Morton"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    },
    "pulp fiction": {
        "title": "Pulp Fiction",
        "year": 1994,
        "directors": [{"id": 138, "name": "Quentin Tarantino"}],
        "cast": [
            {"id": 8891, "name": "John Travolta", "character": "Vincent Vega"},
            {"id": 2231, "name": "Samuel L. Jackson", "character": "Jules Winnfield"},
            {"id": 139, "name": "Uma Thurman", "character": "Mia Wallace"},
            {"id": 62, "name": "Bruce Willis", "character": "Butch Coolidge"},
            {"id": 1064, "name": "Ving Rhames", "character": "Marsellus Wallace"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    },
    "inglourious basterds": {
        "title": "Inglourious Basterds",
        "year": 2009,
        "directors": [{"id": 138, "name": "Quentin Tarantino"}],
        "cast": [
            {"id": 287, "name": "Brad Pitt", "character": "Lt. Aldo Raine"},
            {"id": 27319, "name": "Christoph Waltz", "character": "Col. Hans Landa"},
            {"id": 17018, "name": "Mélanie Laurent", "character": "Shosanna Dreyfus"},
            {"id": 13240, "name": "Michael Fassbender", "character": "Lt. Archie Hicox"},
            {"id": 41091, "name": "Daniel Brühl", "character": "Fredrick Zoller"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/7sfbEnaARXDD5Km0CZ7D7uc2hv1.jpg",
    },
    "once upon a time in hollywood": {
        "title": "Once Upon a Time in Hollywood",
        "year": 2019,
        "directors": [{"id": 138, "name": "Quentin Tarantino"}],
        "cast": [
            {"id": 6193, "name": "Leonardo DiCaprio", "character": "Rick Dalton"},
            {"id": 287, "name": "Brad Pitt", "character": "Cliff Booth"},
            {"id": 234352, "name": "Margot Robbie", "character": "Sharon Tate"},
            {"id": 1158, "name": "Al Pacino", "character": "Marvin Schwarzs"},
            {"id": 139, "name": "Kurt Russell", "character": "Randy Miller"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg",
    },
    "barbie": {
        "title": "Barbie",
        "year": 2023,
        "directors": [{"id": 76595, "name": "Greta Gerwig"}],
        "cast": [
            {"id": 234352, "name": "Margot Robbie", "character": "Barbie"},
            {"id": 30614, "name": "Ryan Gosling", "character": "Ken"},
            {"id": 11701, "name": "America Ferrera", "character": "Gloria"},
            {"id": 23659, "name": "Will Ferrell", "character": "Mattel CEO"},
            {"id": 169337, "name": "Simu Liu", "character": "Ken"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    },
    "little women": {
        "title": "Little Women",
        "year": 2019,
        "directors": [{"id": 76595, "name": "Greta Gerwig"}],
        "cast": [
            {"id": 10993, "name": "Saoirse Ronan", "character": "Jo March"},
            {"id": 1373737, "name": "Florence Pugh", "character": "Amy March"},
            {"id": 1190668, "name": "Timothée Chalamet", "character": "Laurie"},
            {"id": 10990, "name": "Emma Watson", "character": "Meg March"},
            {"id": 5064, "name": "Meryl Streep", "character": "Aunt March"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/yn5ih0VhZflthMEBhPPILn0R9nw.jpg",
    },
    "lady bird": {
        "title": "Lady Bird",
        "year": 2017,
        "directors": [{"id": 76595, "name": "Greta Gerwig"}],
        "cast": [
            {"id": 10993, "name": "Saoirse Ronan", "character": "Lady Bird McPherson"},
            {"id": 1190668, "name": "Timothée Chalamet", "character": "Kyle Scheible"},
            {"id": 12117, "name": "Laurie Metcalf", "character": "Marion McPherson"},
            {"id": 1585885, "name": "Lucas Hedges", "character": "Danny O'Neill"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/iy4R9gnRhAU1ykR2iZ4bcv9Z3G2.jpg",
    },
    "killers of the flower moon": {
        "title": "Killers of the Flower Moon",
        "year": 2023,
        "directors": [{"id": 1032, "name": "Martin Scorsese"}],
        "cast": [
            {"id": 6193, "name": "Leonardo DiCaprio", "character": "Ernest Burkhart"},
            {"id": 380, "name": "Robert De Niro", "character": "William King Hale"},
            {"id": 2697858, "name": "Lily Gladstone", "character": "Mollie Burkhart"},
            {"id": 17838, "name": "Jesse Plemons", "character": "Tom White"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg",
    },
    "the wolf of wall street": {
        "title": "The Wolf of Wall Street",
        "year": 2013,
        "directors": [{"id": 1032, "name": "Martin Scorsese"}],
        "cast": [
            {"id": 6193, "name": "Leonardo DiCaprio", "character": "Jordan Belfort"},
            {"id": 19492, "name": "Jonah Hill", "character": "Donnie Azoff"},
            {"id": 234352, "name": "Margot Robbie", "character": "Naomi Lapaglia"},
            {"id": 10297, "name": "Matthew McConaughey", "character": "Mark Hanna"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/34m2tygAYBGqA9MXKhRDtzYd4MR.jpg",
    },
    "the Irishman": {
        "title": "The Irishman",
        "year": 2019,
        "directors": [{"id": 1032, "name": "Martin Scorsese"}],
        "cast": [
            {"id": 380, "name": "Robert De Niro", "character": "Frank Sheeran"},
            {"id": 1158, "name": "Al Pacino", "character": "Jimmy Hoffa"},
            {"id": 4545, "name": "Joe Pesci", "character": "Russell Bufalino"},
            {"id": 69, "name": "Harvey Keitel", "character": "Angelo Bruno"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/mbm8k3GFhXS0aM9926Ka7krIHof.jpg",
    },
    "parasite": {
        "title": "Parasite",
        "year": 2019,
        "directors": [{"id": 21684, "name": "Bong Joon-ho"}],
        "cast": [
            {"id": 20738, "name": "Song Kang-ho", "character": "Kim Ki-taek"},
            {"id": 1283307, "name": "Lee Sun-kyun", "character": "Park Dong-ik"},
            {"id": 1116246, "name": "Cho Yeo-jeong", "character": "Choi Yeon-gyo"},
            {"id": 1253360, "name": "Choi Woo-shik", "character": "Kim Ki-woo"},
            {"id": 1509318, "name": "Park So-dam", "character": "Kim Ki-jung"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    },
    "memories of murder": {
        "title": "Memories of Murder",
        "year": 2003,
        "directors": [{"id": 21684, "name": "Bong Joon-ho"}],
        "cast": [
            {"id": 20738, "name": "Song Kang-ho", "character": "Park Doo-man"},
            {"id": 78877, "name": "Kim Sang-kyung", "character": "Seo Tae-yoon"},
            {"id": 1253361, "name": "Kim Roi-ha", "character": "Cho Yong-koo"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/fnbjc28B0n4T25uVvj3WdY45K1n.jpg",
    },
    "poor things": {
        "title": "Poor Things",
        "year": 2023,
        "directors": [{"id": 55850, "name": "Yorgos Lanthimos"}],
        "cast": [
            {"id": 54693, "name": "Emma Stone", "character": "Bella Baxter"},
            {"id": 5293, "name": "Willem Dafoe", "character": "Dr. Godwin Baxter"},
            {"id": 103, "name": "Mark Ruffalo", "character": "Duncan Wedderburn"},
            {"id": 1253362, "name": "Ramy Youssef", "character": "Max McCandles"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
    },
    "the favourite": {
        "title": "The Favourite",
        "year": 2018,
        "directors": [{"id": 55850, "name": "Yorgos Lanthimos"}],
        "cast": [
            {"id": 39187, "name": "Olivia Colman", "character": "Queen Anne"},
            {"id": 54693, "name": "Emma Stone", "character": "Abigail Masham"},
            {"id": 112, "name": "Rachel Weisz", "character": "Lady Sarah"},
            {"id": 139, "name": "Nicholas Hoult", "character": "Robert Harley"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/4BgAyw949hT9o12qVzM6w5M6e.jpg",
    },
    "la la land": {
        "title": "La La Land",
        "year": 2016,
        "directors": [{"id": 130101, "name": "Damien Chazelle"}],
        "cast": [
            {"id": 30614, "name": "Ryan Gosling", "character": "Sebastian Wilder"},
            {"id": 54693, "name": "Emma Stone", "character": "Mia Dolan"},
            {"id": 18974, "name": "John Legend", "character": "Keith"},
            {"id": 4173, "name": "J.K. Simmons", "character": "Bill"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/uDO8zWDhfWwoFdKS4fzkVJt0Rf0.jpg",
    },
    "whiplash": {
        "title": "Whiplash",
        "year": 2014,
        "directors": [{"id": 130101, "name": "Damien Chazelle"}],
        "cast": [
            {"id": 2180, "name": "Miles Teller", "character": "Andrew Neiman"},
            {"id": 4173, "name": "J.K. Simmons", "character": "Terence Fletcher"},
            {"id": 84497, "name": "Paul Reiser", "character": "Jim Neiman"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    },
    "get out": {
        "title": "Get Out",
        "year": 2017,
        "directors": [{"id": 236851, "name": "Jordan Peele"}],
        "cast": [
            {"id": 974169, "name": "Daniel Kaluuya", "character": "Chris Washington"},
            {"id": 140417, "name": "Allison Williams", "character": "Rose Armitage"},
            {"id": 59258, "name": "Bradley Whitford", "character": "Dean Armitage"},
            {"id": 17838, "name": "Catherine Keener", "character": "Missy Armitage"},
            {"id": 1083010, "name": "Lakeith Stanfield", "character": "Andre Hayworth"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
    },
    "nope": {
        "title": "Nope",
        "year": 2022,
        "directors": [{"id": 236851, "name": "Jordan Peele"}],
        "cast": [
            {"id": 974169, "name": "Daniel Kaluuya", "character": "OJ Haywood"},
            {"id": 111100, "name": "Keke Palmer", "character": "Emerald Haywood"},
            {"id": 1253363, "name": "Steven Yeun", "character": "Ricky 'Jupe' Park"},
            {"id": 117642, "name": "Michael Wincott", "character": "Antlers Holst"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/AcKVlWaNVVVFQwro3nLXqPlLoxl.jpg",
    },
    "fight club": {
        "title": "Fight Club",
        "year": 1999,
        "directors": [{"id": 7467, "name": "David Fincher"}],
        "cast": [
            {"id": 819, "name": "Edward Norton", "character": "The Narrator"},
            {"id": 287, "name": "Brad Pitt", "character": "Tyler Durden"},
            {"id": 1283, "name": "Helena Bonham Carter", "character": "Marla Singer"},
            {"id": 7499, "name": "Jared Leto", "character": "Angel Face"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    },
    "the social network": {
        "title": "The Social Network",
        "year": 2010,
        "directors": [{"id": 7467, "name": "David Fincher"}],
        "cast": [
            {"id": 44710, "name": "Jesse Eisenberg", "character": "Mark Zuckerberg"},
            {"id": 37632, "name": "Andrew Garfield", "character": "Eduardo Saverin"},
            {"id": 7879, "name": "Justin Timberlake", "character": "Sean Parker"},
            {"id": 18050, "name": "Rooney Mara", "character": "Erica Albright"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/n0ybibhJtQ5icDqTpTcvRnv07ap.jpg",
    },
    "se7en": {
        "title": "Se7en",
        "year": 1995,
        "directors": [{"id": 7467, "name": "David Fincher"}],
        "cast": [
            {"id": 287, "name": "Brad Pitt", "character": "Detective David Mills"},
            {"id": 192, "name": "Morgan Freeman", "character": "Detective William Somerset"},
            {"id": 12052, "name": "Gwyneth Paltrow", "character": "Tracy Mills"},
            {"id": 1979, "name": "Kevin Spacey", "character": "John Doe"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/6yoghtyTpznpBik8EngEmJsk9UO.jpg",
    },
    "the grand budapest hotel": {
        "title": "The Grand Budapest Hotel",
        "year": 2014,
        "directors": [{"id": 5655, "name": "Wes Anderson"}],
        "cast": [
            {"id": 5469, "name": "Ralph Fiennes", "character": "M. Gustave"},
            {"id": 5293, "name": "Willem Dafoe", "character": "J.G. Jopling"},
            {"id": 3063, "name": "Tilda Swinton", "character": "Madame D."},
            {"id": 1532, "name": "Bill Murray", "character": "M. Ivan"},
            {"id": 17838, "name": "Saoirse Ronan", "character": "Agatha"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/eWdyYQreja6JGCzqHWX9NZkt5BW.jpg",
    },
    "asteroid city": {
        "title": "Asteroid City",
        "year": 2023,
        "directors": [{"id": 5655, "name": "Wes Anderson"}],
        "cast": [
            {"id": 2440, "name": "Jason Schwartzman", "character": "Augie Steenbeck"},
            {"id": 1245, "name": "Scarlett Johansson", "character": "Midge Campbell"},
            {"id": 31, "name": "Tom Hanks", "character": "Stanley Zak"},
            {"id": 5293, "name": "Willem Dafoe", "character": "Saltzburg Keitel"},
            {"id": 234352, "name": "Margot Robbie", "character": "Steenbeck's Deceased Wife"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/qdq40R8on1GlsP09h9gJ2u3c244.jpg",
    },
    "spirited away": {
        "title": "Spirited Away",
        "year": 2001,
        "directors": [{"id": 608, "name": "Hayao Miyazaki"}],
        "cast": [
            {"id": 19586, "name": "Rumi Hiiragi", "character": "Chihiro Ogino"},
            {"id": 19587, "name": "Miyu Irino", "character": "Haku"},
            {"id": 19588, "name": "Mari Natsuki", "character": "Yubaba / Zeniba"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/393rws241gUoQ6oTzB2F7jQjKec.jpg",
    },
    "princess mononoke": {
        "title": "Princess Mononoke",
        "year": 1997,
        "directors": [{"id": 608, "name": "Hayao Miyazaki"}],
        "cast": [
            {"id": 19589, "name": "Yoji Matsuda", "character": "Ashitaka"},
            {"id": 19590, "name": "Yuriko Ishida", "character": "San"},
            {"id": 19591, "name": "Yuko Tanaka", "character": "Lady Eboshi"},
        ],
        "poster_path": "https://image.tmdb.org/t/p/w300/cmyDbVv609gA2h4Y1XwM3e99J0l.jpg",
    },
}

# Sample profile 1: "Cinephile Alex"
SAMPLE_PROFILE_ALEX = [
    {"title": "Oppenheimer", "year": 2023},
    {"title": "Interstellar", "year": 2014},
    {"title": "Inception", "year": 2010},
    {"title": "The Dark Knight", "year": 2008},
    {"title": "Dune: Part Two", "year": 2024},
    {"title": "Dune", "year": 2021},
    {"title": "Blade Runner 2049", "year": 2017},
    {"title": "Pulp Fiction", "year": 1994},
    {"title": "Inglourious Basterds", "year": 2009},
    {"title": "Once Upon a Time in Hollywood", "year": 2019},
    {"title": "Killers of the Flower Moon", "year": 2023},
    {"title": "The Wolf of Wall Street", "year": 2013},
    {"title": "The Irishman", "year": 2019},
    {"title": "Fight Club", "year": 1999},
    {"title": "The Social Network", "year": 2010},
    {"title": "Se7en", "year": 1995},
    {"title": "Parasite", "year": 2019},
    {"title": "Memories of Murder", "year": 2003},
    {"title": "Poor Things", "year": 2023},
    {"title": "The Favourite", "year": 2018},
    {"title": "La La Land", "year": 2016},
    {"title": "Whiplash", "year": 2014},
    {"title": "Get Out", "year": 2017},
    {"title": "Nope", "year": 2022},
    {"title": "The Grand Budapest Hotel", "year": 2014},
    {"title": "Asteroid City", "year": 2023},
    {"title": "Spirited Away", "year": 2001},
    {"title": "Princess Mononoke", "year": 1997},
    {"title": "Barbie", "year": 2023},
    {"title": "Little Women", "year": 2019},
]

# Sample profile 2: "Film Buff Taylor" (Comparison user)
SAMPLE_PROFILE_TAYLOR = [
    {"title": "Barbie", "year": 2023},
    {"title": "Little Women", "year": 2019},
    {"title": "Lady Bird", "year": 2017},
    {"title": "Poor Things", "year": 2023},
    {"title": "The Favourite", "year": 2018},
    {"title": "La La Land", "year": 2016},
    {"title": "Whiplash", "year": 2014},
    {"title": "Dune: Part Two", "year": 2024},
    {"title": "Dune", "year": 2021},
    {"title": "The Grand Budapest Hotel", "year": 2014},
    {"title": "Asteroid City", "year": 2023},
    {"title": "Parasite", "year": 2019},
    {"title": "Get Out", "year": 2017},
    {"title": "Nope", "year": 2022},
    {"title": "Oppenheimer", "year": 2023},
    {"title": "Once Upon a Time in Hollywood", "year": 2019},
    {"title": "Spirited Away", "year": 2001},
    {"title": "Princess Mononoke", "year": 1997},
]
